from pathlib import Path


ROOT = Path(__file__).resolve().parent
MODULE_COUNT = 14
ITEM_GROUPS_PER_MODULE = 115


def main() -> None:
    write_workspace()
    write_crate()


def write_workspace() -> None:
    write(
        ROOT / "Cargo.toml",
        """[workspace]
members = ["crates/items"]
resolver = "3"
""",
    )


def write_crate() -> None:
    crate = ROOT / "crates/items"
    write(
        crate / "Cargo.toml",
        """[package]
name = "bench_item_tree_heavy"
version = "0.1.0"
edition = "2024"
""",
    )

    modules = "\n".join(f"pub mod module_{module:02};" for module in range(MODULE_COUNT))
    write(
        crate / "src/lib.rs",
        generated_header()
        + f"""#![allow(dead_code)]
#![allow(non_camel_case_types)]

{modules}

pub trait SharedItemTreeTrait {{
    type Output;
    const FACTOR: usize;
}}
""",
    )

    for module in range(MODULE_COUNT):
        write(crate / f"src/module_{module:02}.rs", module_source(module))


def module_source(module: int) -> str:
    sections = [
        generated_header(),
        "use crate::SharedItemTreeTrait;",
        "",
        f"pub const MODULE_{module:02}_BASE: usize = {module};",
    ]

    for idx in range(ITEM_GROUPS_PER_MODULE):
        sections.append(item_group(module, idx))

    return "\n\n".join(sections) + "\n"


def item_group(module: int, idx: int) -> str:
    fields = "\n".join(
        f"    pub field_{field}: Option<Result<usize, &'static str>>,"
        for field in range(5)
    )
    variants = "\n".join(
        f"    Variant{variant}(ItemStruct_{module:02}_{idx:03}<usize, {variant + 1}>),"
        for variant in range(4)
    )

    return f"""#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ItemStruct_{module:02}_{idx:03}<T, const N: usize>
where
    T: Clone + core::fmt::Debug,
{{
    pub value: T,
    pub slots: [usize; N],
{fields}
}}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ItemEnum_{module:02}_{idx:03} {{
    Empty,
{variants}
    Struct {{ name: &'static str, value: usize }},
}}

pub type ItemAlias_{module:02}_{idx:03}<T, const N: usize> = Result<
    (ItemStruct_{module:02}_{idx:03}<T, N>, Option<ItemEnum_{module:02}_{idx:03}>),
    &'static str,
>;

pub trait ItemTrait_{module:02}_{idx:03}<T>
where
    T: Clone + core::fmt::Debug,
{{
    type Assoc;
    const ID: usize;
}}

impl<T, const N: usize> ItemStruct_{module:02}_{idx:03}<T, N>
where
    T: Clone + core::fmt::Debug + Default,
{{
    pub const LOCAL_ID: usize = {module * 1000 + idx};
}}

impl<T, const N: usize> SharedItemTreeTrait for ItemStruct_{module:02}_{idx:03}<T, N>
where
    T: Clone + core::fmt::Debug + Default,
{{
    type Output = T;
    const FACTOR: usize = N + {idx};
}}

impl<T, const N: usize> ItemTrait_{module:02}_{idx:03}<T> for ItemStruct_{module:02}_{idx:03}<T, N>
where
    T: Clone + core::fmt::Debug + Default,
{{
    type Assoc = ItemAlias_{module:02}_{idx:03}<T, N>;
    const ID: usize = {module * 1000 + idx};
}}

pub static ITEM_STATIC_{module:02}_{idx:03}: usize = {idx};
pub const ITEM_CONST_{module:02}_{idx:03}: usize = MODULE_{module:02}_BASE + {idx};"""


def generated_header() -> str:
    return "// Generated by generate.py. Do not edit by hand.\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
