from pathlib import Path


ROOT = Path(__file__).resolve().parent
MODULE_COUNT = 10
ALIASES_PER_MODULE = 140
FUNCTIONS_PER_MODULE = 0
MACROS_PER_MODULE = 60


def main() -> None:
    write_workspace()
    write_crate()


def write_workspace() -> None:
    write(
        ROOT / "Cargo.toml",
        """[workspace]
members = ["crates/parse"]
resolver = "3"
""",
    )


def write_crate() -> None:
    crate = ROOT / "crates/parse"
    write(
        crate / "Cargo.toml",
        """[package]
name = "bench_parse_heavy"
version = "0.1.0"
edition = "2024"
""",
    )

    for old_module in (crate / "src").glob("chunk_*.rs"):
        old_module.unlink()

    chunks = "\n\n".join(inline_module(module) for module in range(MODULE_COUNT))
    write(
        crate / "src/lib.rs",
        generated_header()
        + f"""#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(unused_attributes)]
#![allow(unused_macros)]

{chunks}
""",
    )


def inline_module(module: int) -> str:
    return f"pub mod chunk_{module:02} {{\n{indent(module_source(module))}\n}}"


def module_source(module: int) -> str:
    sections = [
        generated_header(),
        "#![allow(non_camel_case_types)]",
        "#![allow(unused_attributes)]",
        "",
        f"pub const MODULE_{module:02}: usize = {module};",
    ]

    for idx in range(ALIASES_PER_MODULE):
        sections.append(type_alias(module, idx))

    for idx in range(MACROS_PER_MODULE):
        sections.append(macro_call(module, idx))

    for idx in range(FUNCTIONS_PER_MODULE):
        sections.append(function_signature(module, idx))

    return "\n\n".join(sections) + "\n"


def indent(text: str) -> str:
    return "\n".join(f"    {line}" if line else "" for line in text.splitlines())


def type_alias(module: int, idx: int) -> str:
    fields = ", ".join(
        f"Option<Result<&'static [u8; {module + idx + field + 1}], &'static str>>"
        for field in range(6)
    )
    docs = "\n".join(
        f"/// Parser-heavy alias {module:02}_{idx:03} documentation sentence {line} "
        f"with punctuation, paths like crate::chunk_{module:02}, and generic-looking text <T{line}>."
        for line in range(4)
    )

    return f"""{docs}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ParseRecord_{module:02}_{idx:03}<T, const N: usize>
where
    T: Copy + core::fmt::Debug,
{{
    pub id: usize,
    pub payload: T,
    pub slots: [usize; N],
}}

pub type ParseAlias_{module:02}_{idx:03}<T> = (
    ParseRecord_{module:02}_{idx:03}<T, {idx % 8 + 1}>,
    Result<({fields}), &'static str>,
    [Option<T>; {idx % 5 + 1}],
);"""


def macro_call(module: int, idx: int) -> str:
    entries = ", ".join(
        f"(key_{module:02}_{idx:02}_{entry}: [{entry}, {entry + 1}, {entry + 2}])"
        for entry in range(12)
    )

    return f"""macro_rules! parse_macro_{module:02}_{idx:02} {{
    ($name:ident, $value:expr, $($tail:tt)*) => {{
        pub const $name: usize = $value;
    }};
}}

parse_macro_{module:02}_{idx:02}!(PARSE_MACRO_VALUE_{module:02}_{idx:02}, {module * 1000 + idx}, {entries});"""


def function_signature(module: int, idx: int) -> str:
    args = ", ".join(
        f"arg_{arg}: Option<ParseAlias_{module:02}_{(idx + arg) % ALIASES_PER_MODULE:03}<usize>>"
        for arg in range(4)
    )
    where_items = "\n    ".join(
        [
            "for<'a> &'a T: IntoIterator<Item = &'a usize>,",
            "T: Clone + core::fmt::Debug + Default,",
            "[usize; 4]: Default,",
        ]
    )

    return f"""pub trait ParseSignatureTrait_{module:02}_{idx:03} {{
    fn parse_function_{module:02}_{idx:03}<T>({args}) -> usize
where
    {where_items}
    ;
}}"""


def generated_header() -> str:
    return "// Generated by generate.py. Do not edit by hand.\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
